# Generated by Django 6.0.4 on 2026-04-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=15)),
                ('health', models.CharField(max_length=100)),
                ('enclosure_id', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enclosures_id', models.IntegerField(max_length=50)),
                ('descriptoins', models.CharField(max_length=100)),
                ('size', models.IntegerField(max_length=100)),
            ],
        ),
    ]
